services:
  core-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start
    env_file:
      - ./.env
    environment:
      - DB_HOST=postgres #  this is useful since localhost is not accessible from the container
      - DB_PORT=5432 # Use PostgreSQL's default internal port
      - REDIS_URL=redis://:dXf9TMBjMLxUCfz6HG57@redis:6379/1
      - RABBITMQ_URI=amqp://rabbitmq:5672
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    ports:
      - '3000:3000'
      - '50055:50055'
volumes:
  caddy_data:
  caddy_config:
